(function(global){
  'use strict';

  function latin1Bytes(text){
    const bytes=new Uint8Array(text.length);
    for(let i=0;i<text.length;i++) bytes[i]=text.charCodeAt(i)&255;
    return bytes;
  }

  function pdfText(value){
    return String(value??'')
      .replace(/[^\x20-\x7E]/g,' ')
      .replace(/\\/g,'\\\\').replace(/\(/g,'\\(').replace(/\)/g,'\\)');
  }

  function safeFilePart(value){
    return String(value||'certificate').replace(/[^a-zA-Z0-9_-]+/g,'-').replace(/^-+|-+$/g,'').slice(0,80)||'certificate';
  }

  function centerText(text,fontSize,pageWidth){
    // Helvetica average glyph width is roughly 0.5 em; sufficient for centered certificate lines.
    return Math.max(38,(pageWidth-(String(text).length*fontSize*0.5))/2);
  }

  function wrapText(text,maxChars){
    const words=String(text||'').trim().split(/\s+/).filter(Boolean),lines=[];
    let line='';
    for(const word of words){
      const next=line?line+' '+word:word;
      if(next.length>maxChars&&line){lines.push(line);line=word;}else line=next;
    }
    if(line)lines.push(line);
    return lines.slice(0,3);
  }

  function buildCertificatePdf(data){
    const W=842,H=595;
    const donor=pdfText(data.donor||'Pi donor');
    const campaign=pdfText(data.campaign||'Donate Way campaign');
    const amount=Number(data.amount||0).toFixed(2)+' Pi';
    const donationDate=pdfText(data.date||'');
    const certificateId=pdfText(data.certificateId||'DW-CERT');
    const transactionId=pdfText(data.transactionId||'Not available');
    const publicDisplay=data.isAnonymous?'Anonymous':'@'+donor;
    const campaignLines=wrapText(campaign,58);

    const c=[];
    c.push('q');
    c.push('0.975 0.97 1 rg 0 0 842 595 re f');
    c.push('0.43 0.16 0.85 RG 4 w 24 24 794 547 re S');
    c.push('0.82 0.75 0.98 RG 1.2 w 34 34 774 527 re S');
    c.push('0.43 0.16 0.85 rg 62 520 718 3 re f');
    c.push('0.43 0.16 0.85 rg 62 72 718 3 re f');

    const text=(font,size,x,y,value,gray='0.08 0.10 0.16')=>{
      c.push('BT'); c.push(`/${font} ${size} Tf`); c.push(`${gray} rg`); c.push(`1 0 0 1 ${x.toFixed(2)} ${y.toFixed(2)} Tm`); c.push(`(${pdfText(value)}) Tj`); c.push('ET');
    };
    const centered=(font,size,y,value,gray)=>text(font,size,centerText(value,size,W),y,value,gray);

    centered('F2',27,474,'DONATE WAY','0.43 0.16 0.85');
    centered('F2',18,438,'CERTIFICATE OF DONATION');
    centered('F1',10.5,414,'This certificate confirms a donation recorded from a server-verified Pi payment.','0.36 0.40 0.49');
    centered('F1',11,374,'Presented to','0.36 0.40 0.49');
    centered('F2',25,340,'@'+donor,'0.08 0.10 0.16');
    centered('F1',11,314,'for supporting','0.36 0.40 0.49');

    let cy=281;
    for(const line of campaignLines){centered('F2',16,cy,line,'0.12 0.14 0.20');cy-=20;}

    centered('F2',26,218,amount,'0.43 0.16 0.85');

    c.push('0.92 0.90 0.98 rg 130 120 582 72 re f');
    text('F2',9.5,150,170,'DONATION DATE','0.36 0.40 0.49');
    text('F1',10.5,150,151,donationDate);
    text('F2',9.5,330,170,'PUBLIC DISPLAY','0.36 0.40 0.49');
    text('F1',10.5,330,151,pdfText(publicDisplay));
    text('F2',9.5,520,170,'CERTIFICATE ID','0.36 0.40 0.49');
    text('F1',9.3,520,151,certificateId);

    centered('F1',8.5,96,'Transaction reference: '+transactionId,'0.36 0.40 0.49');
    centered('F1',8.5,52,'Generated by Donate Way from the donor\'s verified donation record.','0.36 0.40 0.49');
    c.push('Q');

    const stream=c.join('\n');
    const objects=[
      '<< /Type /Catalog /Pages 2 0 R >>',
      '<< /Type /Pages /Kids [3 0 R] /Count 1 >>',
      '<< /Type /Page /Parent 2 0 R /MediaBox [0 0 842 595] /Resources << /Font << /F1 5 0 R /F2 6 0 R >> >> /Contents 4 0 R >>',
      `<< /Length ${latin1Bytes(stream).length} >>\nstream\n${stream}\nendstream`,
      '<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>',
      '<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica-Bold >>'
    ];

    let pdf='%PDF-1.4\n%\xE2\xE3\xCF\xD3\n',offsets=[0];
    for(let i=0;i<objects.length;i++){
      offsets.push(latin1Bytes(pdf).length);
      pdf+=`${i+1} 0 obj\n${objects[i]}\nendobj\n`;
    }
    const xref=latin1Bytes(pdf).length;
    pdf+=`xref\n0 ${objects.length+1}\n0000000000 65535 f \n`;
    for(let i=1;i<offsets.length;i++) pdf+=String(offsets[i]).padStart(10,'0')+' 00000 n \n';
    pdf+=`trailer\n<< /Size ${objects.length+1} /Root 1 0 R >>\nstartxref\n${xref}\n%%EOF`;
    return new Blob([latin1Bytes(pdf)],{type:'application/pdf'});
  }

  function downloadDonationCertificate(data){
    const blob=buildCertificatePdf(data);
    const url=URL.createObjectURL(blob);
    const a=document.createElement('a');
    a.href=url;
    a.download=`Donate-Way-Certificate-${safeFilePart(data.certificateId)}.pdf`;
    document.body.appendChild(a); a.click(); a.remove();
    setTimeout(()=>URL.revokeObjectURL(url),30000);
  }

  global.DonateWayCertificate={buildCertificatePdf,downloadDonationCertificate};
})(window);
